### ISSUE TITLE
Data retention

### ISSUE THREAD

**Issue by docent-net** [bleemeo/squirreldb#1]
Hi,

I'm just starting to evaluate Squirreldb in terms of long-term storage for Prometheus. Got a question related to data retention. So let's say - I'm interested in keeping only 2 years of metrics inside squirreldb. How do you achieve this?

My educated guess would be, that there's a need for updating data in Cassandra rows, marking it as deleted (so a basic DELETE query). This would generate tombstones which would be removed during the next compaction process.

However, the other way around would be to set data invalidation (via TTLs) during data creation process (so in practice, setting TTLs on new data imported from prometheus).

So, having this said - could you elaborate a bit about this? Haven't found this kind of information. In return, I can create documentation for this when I test it ;) Thanks

**Comment by PierreF** [comment]
Hi,

As you guessed, we achieve retention via TTLs at ingestion time. We do not explicitly mark them as deleted and only rely on Cassandra's TTLs.

We choose this solution to be compaction friendly: once inserted data never change even for the tombstone marker. This guarantee that any point is only stored in one data file, Cassandra don't need to scan more than one file for a potential tombstone marker.

This solutions had the drawback that retention must be choose at ingestion time, and changing the retention only apply to  new ingested points.

There is two way to set the retention:
* The default setting [default_time_to_live](https://github.com/bleemeo/squirreldb/blob/92b2d62a8b127b1464771be959003d5221936a7f/squirreldb.conf#L61) from configuration file (or environment variable SQUIRRELDB_CASSANDRA_DEFAULT_TIME_TO_LIVE). The default value is 1 year.
* Write the metric with a special label `__ttl__` that override the default only for that point. This label is not persisted (it won't be shown when querying) and only used to choose the time to live of the ingested point.

The first option is the best if all you data use the same retention. The second option is useful when you have multiple source with different retention policy per source.

For a unique retention policy of 2 year, assuming you use Docker for running SquirrelDB, the solution would be to add `-e SQUIRRELDB_CASSANDRA_DEFAULT_TIME_TO_LIVE=17520h` to your docker run.

Does it answer your question or do you want further details ?

**Comment by docent-net** [comment]
I'm truly sorry for this late reply - must have missed the notification.

Yes, your answer is more than enough, thank you!

**Comment by PierreF** [comment]
You're welcome. If you have other questions, I'll be happy to answer them.
